### PR TITLE
caravan image

### PR DESCRIPTION
**Pull request by nigelwhite**
Friday at 1pm

### CODE REVIEW

**Comment by nigelwhite** [comment]
Something funny happened. I didn't expect a conflict.
Oh, looks like I started with a non-master version of myaunt.txt, so I've added some lines where some lines already are. I'll try to sort it out....

**Comment by nigelwhite** [comment]
I have edited the file so there are no conflicts in there, but github is still saying "this branch has conflicts". Not sure what to do next.... Will try to leave a comment here.

**Comment by nigelwhite** [comment]
Ah, got it.
I went into the web editor, did manual edits.
Then clicked Mark as Resolved
Then Commit Merge (a new button that appears after you've Marked as Resolved)
Now the system has queued up a Pull Request that no longer conflicts...
Phew....

**Review by Nicolabell — APPROVED** [review]
I see! Hopefully this should now be merged...it looks like it is already on gitkraken which is confusing!!

**Pull request merged**
